sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: WYC5552374
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: # 注意填充id
    access-key-secret: # 注意填充密码
    bucket-name: icyyybro-sky